In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy version: 2.2.5
Pandas version: 2.2.3

In [3]:
df_hq = pd.read_csv("./ds/Procedimiento1Hojadequirofano_20250424_utf-8.csv")
df_np = pd.read_csv("./ds/Procedimiento2NotaPostoperatoria_20250424_utf-8.csv")
df_hi = pd.read_csv("./ds/Procedimiento3Hojadeintervencionismo_20250424_utf-8.csv")

## Ajustar los datos de la Hoja de quirófano

In [4]:
df_hq.shape

(271, 14)

In [5]:
df_hq.describe(include='object').transpose()

,count,unique,top,freq
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre),266,224,MARCO ANTONIO,4
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido),266,167,HERNANDEZ,13
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido),266,173,HERNANDEZ,12
Fecha y Hora Registro,271,261,,9
Fecha y Hora de Egreso,271,261,,9
Fecha y hora de elaboración,271,271,30.Nov.23 11:20:00,1
Tipo de Ingreso,271,3,ADMISIÓN HOSPITALARIA,186
Hospitalizado en,271,13,Servicio Clínico 8,126
Cirugía realizada - CIE 9 Tratamientos - Clave,92,26,2188,16
Cirugía realizada - CIE 9 Tratamientos - Descripción,92,24,Otra septoplastia,16
Clave,92,26,2188,16
Descripción,92,24,Otra septoplastia,16

In [6]:
df_hq.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      float64
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Cirugía realizada - CIE 9 Tratamientos - Clave                                           object
Cirugía realizada - CIE 9 Tratamientos - Descripción                                     object
Clave                                                                                    object
Descripción                                                                              object
dtype: object

In [7]:
df_hq = df_hq.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Cirugía realizada - CIE 9 Tratamientos - Clave',
                              'Cirugía realizada - CIE 9 Tratamientos - Descripción'])

In [8]:
df_hq.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

In [10]:
df_hq.info

<bound method DataFrame.info of      Expediente            Registro              Egreso         Elaboracion  \
0      248277.0  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 09:40:00
1      236422.0  11.Ene.23 15:48:18  12.Ene.23 19:05:18  12.Ene.23 08:41:00
2      209000.0  10.Ene.23 15:32:44  12.Ene.23 13:12:16  11.Ene.23 09:52:00
3      243590.0  10.Ene.23 15:23:31  11.Ene.23 18:02:14  11.Ene.23 10:56:00
4      248153.0  11.Ene.23 09:40:52  11.Ene.23 15:29:00  11.Ene.23 13:24:00
..          ...                 ...                 ...                 ...
266    216626.0  25.Oct.23 07:09:38  25.Oct.23 19:03:13  25.Oct.23 09:32:00
267         NaN                                          23.Oct.23 11:35:00
268    250094.0  23.Oct.23 11:08:32  25.Oct.23 14:59:41  24.Oct.23 10:45:00
269    239002.0  01.Nov.23 07:38:17  01.Nov.23 19:34:47  01.Nov.23 10:49:00
270    253011.0  29.Nov.23 15:11:54  03.Dic.23 16:27:53  30.Nov.23 11:20:00

                    TipoIngreso             Servicio Clave  \
0        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
2        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    195
3        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
4    PROCEDIMIENTO AMBULATORIO           Quirófanos   3322
..                          ...                  ...   ...
266  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
267                                                    NaN
268      ADMISIÓN HOSPITALARIA   Servicio Clínico 4   3328
269  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
270      ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN

                   Descripcion
0                          NaN
1                          NaN
2          Otra timpanoplastia
3                          NaN
4     Broncoscopia fibroóptica
..                         ...
266                        NaN
267                        NaN
268  Biopsia abierta de pulmón
269                        NaN
270                        NaN

[271 rows x 8 columns]>

In [11]:
df_hq.dropna(subset="Expediente").info

<bound method DataFrame.info of      Expediente            Registro              Egreso         Elaboracion  \
0      248277.0  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 09:40:00
1      236422.0  11.Ene.23 15:48:18  12.Ene.23 19:05:18  12.Ene.23 08:41:00
2      209000.0  10.Ene.23 15:32:44  12.Ene.23 13:12:16  11.Ene.23 09:52:00
3      243590.0  10.Ene.23 15:23:31  11.Ene.23 18:02:14  11.Ene.23 10:56:00
4      248153.0  11.Ene.23 09:40:52  11.Ene.23 15:29:00  11.Ene.23 13:24:00
..          ...                 ...                 ...                 ...
265    253651.0  09.Oct.23 12:51:02  28.Oct.23 14:13:57  17.Oct.23 11:00:00
266    216626.0  25.Oct.23 07:09:38  25.Oct.23 19:03:13  25.Oct.23 09:32:00
268    250094.0  23.Oct.23 11:08:32  25.Oct.23 14:59:41  24.Oct.23 10:45:00
269    239002.0  01.Nov.23 07:38:17  01.Nov.23 19:34:47  01.Nov.23 10:49:00
270    253011.0  29.Nov.23 15:11:54  03.Dic.23 16:27:53  30.Nov.23 11:20:00

                    TipoIngreso             Servicio Clave  \
0        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
2        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    195
3        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
4    PROCEDIMIENTO AMBULATORIO           Quirófanos   3322
..                          ...                  ...   ...
265      ADMISIÓN HOSPITALARIA   Servicio Clínico 2   3241
266  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
268      ADMISIÓN HOSPITALARIA   Servicio Clínico 4   3328
269  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
270      ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN

                               Descripcion
0                                      NaN
1                                      NaN
2                      Otra timpanoplastia
3                                      NaN
4                 Broncoscopia fibroóptica
..                                     ...
265  Lobectomía de pulmón por toracoscopía
266                                    NaN
268              Biopsia abierta de pulmón
269                                    NaN
270                                    NaN

[266 rows x 8 columns]>

## Ajustar datos de la Nota postoperatoria

In [12]:
df_np.shape

(1000, 14)

In [13]:
df_np.describe(include='object').transpose()

,count,unique,top,freq
Expediente / Paciente - Expediente Paciente - Número de Expediente,1000,734,230563,6
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre),1000,559,ALEJANDRO,10
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido),1000,355,HERNANDEZ,40
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido),987,374,HERNANDEZ,33
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento,1000,726,1992-08-05,6
Fecha y Hora Registro,1000,766,,57
Fecha y Hora de Egreso,1000,766,,57
Fecha y hora de Elaboración,1000,954,28.Mar.23 14:47:30,4
Tipo de Ingreso,1000,4,ADMISIÓN HOSPITALARIA,778
Hospitalizado en,1000,12,Servicio Clínico 8,555
Cirugía Realizada,1000,703,RINOSEPTUMPLASTIA FUNCIONAL + ABLACIÓN DE CORN...,29
Clave,1000,220,3142,82
Descripción,1000,213,Laringoscopia y otra traqueoscopia,82

In [14]:
df_np.dtypes

ID Módulo Base                                                                           int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)              object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)     object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)    object
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento                       object
Fecha y Hora Registro                                                                   object
Fecha y Hora de Egreso                                                                  object
Fecha y hora de Elaboración                                                             object
Tipo de Ingreso                                                                         object
Hospitalizado en                                                                        object
Cirugía Realizada                                                                       object
Clave                                                                                   object
Descripción                                                                             object
dtype: object

In [15]:
df_np = df_np.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Fecha de nacimiento',
                              'Cirugía Realizada'])

In [16]:
df_np.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

In [17]:
df_np.info

<bound method DataFrame.info of     Expediente            Registro              Egreso         Elaboracion  \
0       248277  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 10:42:53
1       244031  12.Ene.23 07:58:13  13.Ene.23 11:39:03  12.Ene.23 19:48:34
2       243588  13.Ene.23 06:38:20  13.Ene.23 18:23:57  13.Ene.23 13:27:52
3       246542  23.Ene.23 15:36:55  25.Ene.23 10:07:23  24.Ene.23 11:03:20
4       204124  24.Ene.23 15:41:32  26.Ene.23 10:53:46  25.Ene.23 11:11:58
..         ...                 ...                 ...                 ...
995     254692  24.Nov.23 01:43:36  22.Dic.23 17:12:51  01.Dic.23 16:20:38
996     221315  01.Dic.23 06:48:57  01.Dic.23 16:47:31  01.Dic.23 16:35:17
997     246005  01.Dic.23 07:47:57  03.Dic.23 09:24:55  01.Dic.23 17:49:00
998     253871  30.Nov.23 15:32:50  02.Dic.23 11:53:39  01.Dic.23 18:17:40
999     250693  06.Nov.23 18:18:13  16.Dic.23 18:00:56  02.Dic.23 14:30:46

                    TipoIngreso              Servicio Clave  \
0        ADMISIÓN HOSPITALARIA    Servicio Clínico 8   6731
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 10   2199
2    PROCEDIMIENTO AMBULATORIO       Hospital de Día    219
3        ADMISIÓN HOSPITALARIA    Servicio Clínico 8   3142
4        ADMISIÓN HOSPITALARIA    Servicio Clínico 8    215
..                          ...                   ...   ...
995      ADMISIÓN HOSPITALARIA    Servicio Clínico 1   3406
996  PROCEDIMIENTO AMBULATORIO       Hospital de Día   3322
997      ADMISIÓN HOSPITALARIA    Servicio Clínico 8   3142
998      ADMISIÓN HOSPITALARIA    Servicio Clínico 8   2122
999      ADMISIÓN HOSPITALARIA    Servicio Clínico 9   5122

                                           Descripcion
0                  Marsupialización de quiste cervical
1                        Otra operación sobre la nariz
2                     Otras operaciones sobre la nariz
3                   Laringoscopia y otra traqueoscopia
4    Resección submucosa del tabique nasal (septopl...
..                                                 ...
995        Drenaje de cavidad pleural por toracoscopía
996                           Broncoscopia fibroóptica
997                 Laringoscopia y otra traqueoscopia
998                                   Biopsia de nariz
999                                    Colecistectomía

[1000 rows x 8 columns]>

In [18]:
df_np.dropna(subset="Expediente").info

<bound method DataFrame.info of     Expediente            Registro              Egreso         Elaboracion  \
0       248277  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 10:42:53
1       244031  12.Ene.23 07:58:13  13.Ene.23 11:39:03  12.Ene.23 19:48:34
2       243588  13.Ene.23 06:38:20  13.Ene.23 18:23:57  13.Ene.23 13:27:52
3       246542  23.Ene.23 15:36:55  25.Ene.23 10:07:23  24.Ene.23 11:03:20
4       204124  24.Ene.23 15:41:32  26.Ene.23 10:53:46  25.Ene.23 11:11:58
..         ...                 ...                 ...                 ...
995     254692  24.Nov.23 01:43:36  22.Dic.23 17:12:51  01.Dic.23 16:20:38
996     221315  01.Dic.23 06:48:57  01.Dic.23 16:47:31  01.Dic.23 16:35:17
997     246005  01.Dic.23 07:47:57  03.Dic.23 09:24:55  01.Dic.23 17:49:00
998     253871  30.Nov.23 15:32:50  02.Dic.23 11:53:39  01.Dic.23 18:17:40
999     250693  06.Nov.23 18:18:13  16.Dic.23 18:00:56  02.Dic.23 14:30:46

                    TipoIngreso              Servicio Clave  \
0        ADMISIÓN HOSPITALARIA    Servicio Clínico 8   6731
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 10   2199
2    PROCEDIMIENTO AMBULATORIO       Hospital de Día    219
3        ADMISIÓN HOSPITALARIA    Servicio Clínico 8   3142
4        ADMISIÓN HOSPITALARIA    Servicio Clínico 8    215
..                          ...                   ...   ...
995      ADMISIÓN HOSPITALARIA    Servicio Clínico 1   3406
996  PROCEDIMIENTO AMBULATORIO       Hospital de Día   3322
997      ADMISIÓN HOSPITALARIA    Servicio Clínico 8   3142
998      ADMISIÓN HOSPITALARIA    Servicio Clínico 8   2122
999      ADMISIÓN HOSPITALARIA    Servicio Clínico 9   5122

                                           Descripcion
0                  Marsupialización de quiste cervical
1                        Otra operación sobre la nariz
2                     Otras operaciones sobre la nariz
3                   Laringoscopia y otra traqueoscopia
4    Resección submucosa del tabique nasal (septopl...
..                                                 ...
995        Drenaje de cavidad pleural por toracoscopía
996                           Broncoscopia fibroóptica
997                 Laringoscopia y otra traqueoscopia
998                                   Biopsia de nariz
999                                    Colecistectomía

[1000 rows x 8 columns]>

## Ajustar datos de la Hoja de intervencionismo

In [19]:
df_hi.shape

(898, 14)

In [20]:
df_hi.describe(include='object').transpose()

,count,unique,top,freq
Expediente / Paciente - Expediente Paciente - Número de Expediente,898,621,210636,13
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre),898,463,MARIA,20
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido),898,310,HERNANDEZ,35
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido),893,340,GARCIA,37
Fecha y Hora Registro,898,728,,134
Fecha y Hora de Egreso,898,720,,144
Fecha y hora de elaboración,898,893,18.Sep.23 11:30:00,2
Tipo de Ingreso,898,4,PROCEDIMIENTO AMBULATORIO,542
Hospitalizado en,898,14,Hospital de Día,330
Procedimiento realizado - CIE 9 Tratamientos - Descripción,701,24,Broncoscopia fibroóptica,551
Descripción,701,24,Broncoscopia fibroóptica,551

In [21]:
df_hi.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                       object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Procedimiento realizado - CIE 9 Tratamientos - Clave                                    float64
Procedimiento realizado - CIE 9 Tratamientos - Descripción                               object
Clave                                                                                   float64
Descripción                                                                              object
dtype: object

In [23]:
df_hi = df_hi.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Procedimiento realizado - CIE 9 Tratamientos - Clave',
                              'Procedimiento realizado - CIE 9 Tratamientos - Descripción'])

In [32]:
df_hi.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

In [33]:
df_hi.info

<bound method DataFrame.info of     Expediente            Registro              Egreso         Elaboracion  \
0       247800  20.Dic.22 08:04:34  20.Dic.22 17:20:14  20.Dic.22 12:05:00
1       167293  02.Feb.23 08:02:32  02.Feb.23 15:54:18  02.Feb.23 10:02:00
2       240491  02.Feb.23 07:51:01  02.Feb.23 15:53:54  02.Feb.23 11:35:00
3       246336  02.Feb.23 06:46:43  02.Feb.23 15:54:52  02.Feb.23 08:55:00
4       242564  07.Ene.23 14:25:46  08.Feb.23 14:45:52  02.Feb.23 13:00:00
..         ...                 ...                 ...                 ...
893     255678  25.Ene.24 07:41:20  25.Ene.24 13:29:07  25.Ene.24 12:46:00
894     251834  29.Ene.24 07:04:48  29.Ene.24 11:43:19  29.Ene.24 10:43:00
895     255830  01.Feb.24 06:44:56  01.Feb.24 12:12:32  01.Feb.24 10:03:00
896     253057  01.Feb.24 08:25:49  01.Feb.24 15:39:47  01.Feb.24 11:54:00
897     259448  11.Jun.24 18:26:14  10.Jul.24 16:33:00  11.Jun.24 17:55:00

                    TipoIngreso                        Servicio   Clave  \
0    PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
1    PROCEDIMIENTO AMBULATORIO   Broncoscopia Intervencionista      NaN
2    PROCEDIMIENTO AMBULATORIO   Broncoscopia Intervencionista      NaN
3    PROCEDIMIENTO AMBULATORIO                 Hospital de Día      NaN
4        ADMISIÓN HOSPITALARIA              Servicio Clínico 3    311.0
..                          ...                             ...     ...
893  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
894  PROCEDIMIENTO AMBULATORIO                 Hospital de Día      NaN
895  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
896  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
897      ADMISIÓN HOSPITALARIA              Servicio Clínico 3      NaN

                  Descripcion
0    Broncoscopia fibroóptica
1                         NaN
2                         NaN
3                         NaN
4      Traqueostomía temporal
..                        ...
893  Broncoscopia fibroóptica
894                       NaN
895  Broncoscopia fibroóptica
896  Broncoscopia fibroóptica
897                       NaN

[898 rows x 8 columns]>

In [34]:
df_hi.dropna(subset="Expediente").info

<bound method DataFrame.info of     Expediente            Registro              Egreso         Elaboracion  \
0       247800  20.Dic.22 08:04:34  20.Dic.22 17:20:14  20.Dic.22 12:05:00
1       167293  02.Feb.23 08:02:32  02.Feb.23 15:54:18  02.Feb.23 10:02:00
2       240491  02.Feb.23 07:51:01  02.Feb.23 15:53:54  02.Feb.23 11:35:00
3       246336  02.Feb.23 06:46:43  02.Feb.23 15:54:52  02.Feb.23 08:55:00
4       242564  07.Ene.23 14:25:46  08.Feb.23 14:45:52  02.Feb.23 13:00:00
..         ...                 ...                 ...                 ...
893     255678  25.Ene.24 07:41:20  25.Ene.24 13:29:07  25.Ene.24 12:46:00
894     251834  29.Ene.24 07:04:48  29.Ene.24 11:43:19  29.Ene.24 10:43:00
895     255830  01.Feb.24 06:44:56  01.Feb.24 12:12:32  01.Feb.24 10:03:00
896     253057  01.Feb.24 08:25:49  01.Feb.24 15:39:47  01.Feb.24 11:54:00
897     259448  11.Jun.24 18:26:14  10.Jul.24 16:33:00  11.Jun.24 17:55:00

                    TipoIngreso                        Servicio   Clave  \
0    PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
1    PROCEDIMIENTO AMBULATORIO   Broncoscopia Intervencionista      NaN
2    PROCEDIMIENTO AMBULATORIO   Broncoscopia Intervencionista      NaN
3    PROCEDIMIENTO AMBULATORIO                 Hospital de Día      NaN
4        ADMISIÓN HOSPITALARIA              Servicio Clínico 3    311.0
..                          ...                             ...     ...
893  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
894  PROCEDIMIENTO AMBULATORIO                 Hospital de Día      NaN
895  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
896  PROCEDIMIENTO AMBULATORIO                 Hospital de Día   3322.0
897      ADMISIÓN HOSPITALARIA              Servicio Clínico 3      NaN

                  Descripcion
0    Broncoscopia fibroóptica
1                         NaN
2                         NaN
3                         NaN
4      Traqueostomía temporal
..                        ...
893  Broncoscopia fibroóptica
894                       NaN
895  Broncoscopia fibroóptica
896  Broncoscopia fibroóptica
897                       NaN

[898 rows x 8 columns]>

## Descripción

In [36]:
df_np["Servicio"].value_counts()

Servicio
Servicio Clínico 8                   555
Hospital de Día                      137
Servicio Clínico 1                    60
Servicio Clínico 3                    58
                                      57
Servicio Clínico 4                    46
Servicio Clínico 2                    39
Servicio Clínico 7                    28
Unidad de Terapia Intermedia          10
Servicio Clínico 9                     7
Servicio Clínico 10 Recuperación       2
Servicio Clínico 10                    1
Name: count, dtype: int64

In [40]:
df_np.describe().transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82