In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandasai import SmartDataframe
from langchain_groq.chat_models import ChatGroq

In [2]:
df_hq = pd.read_csv("./ds/Procedimiento1Hojadequirofano_20250424_utf-8.csv")
df_np = pd.read_csv("./ds/Procedimiento2NotaPostoperatoria_20250424_utf-8.csv")
df_hi = pd.read_csv("./ds/Procedimiento3Hojadeintervencionismo_20250424_utf-8.csv")

## Ajustar los datos de la Hoja de quirófano

In [3]:
df_hq.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      float64
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Cirugía realizada - CIE 9 Tratamientos - Clave                                           object
Cirugía realizada - CIE 9 Tratamientos - Descripción                                     object
Clave                                                                                    object
Descripción                                                                              object
dtype: object

In [4]:
df_hq = df_hq.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Cirugía realizada - CIE 9 Tratamientos - Clave',
                              'Cirugía realizada - CIE 9 Tratamientos - Descripción'])

In [5]:
df_hq.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Nota postoperatoria

In [6]:
df_np.dtypes

ID Módulo Base                                                                           int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)              object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)     object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)    object
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento                       object
Fecha y Hora Registro                                                                   object
Fecha y Hora de Egreso                                                                  object
Fecha y hora de Elaboración                                                             object
Tipo de Ingreso                                                                         object
Hospitalizado en                                                                        object
Cirugía Realizada                                                                       object
Clave                                                                                   object
Descripción                                                                             object
dtype: object

In [7]:
df_np = df_np.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Fecha de nacimiento',
                              'Cirugía Realizada'])

In [8]:
df_np.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Hoja de intervencionismo

In [9]:
df_hi.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                       object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Procedimiento realizado - CIE 9 Tratamientos - Clave                                    float64
Procedimiento realizado - CIE 9 Tratamientos - Descripción                               object
Clave                                                                                   float64
Descripción                                                                              object
dtype: object

In [10]:
df_hi = df_hi.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Procedimiento realizado - CIE 9 Tratamientos - Clave',
                              'Procedimiento realizado - CIE 9 Tratamientos - Descripción'])

In [11]:
df_hi.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Descripción

In [12]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 271
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1169

In [13]:
df_hq = df_hq.dropna(subset="Expediente")
df_hi = df_hi.dropna(subset="Expediente")
df_np = df_np.dropna(subset="Expediente")

In [14]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 266
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1164

In [15]:
print(df_np["Clave"].value_counts())

Clave
3142    82
2188    80
3322    45
2187    37
215     32
        ..
3429     1
00G5     1
7        1
348      1
5122     1
Name: count, Length: 220, dtype: int64

In [16]:
df_np.describe().transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [17]:
df_hq.describe(include='object').transpose()

            count unique                     top freq
Registro      266    261                            4
Egreso        266    261                            4
Elaboracion   266    266      30.Nov.23 11:20:00    1
TipoIngreso   266      3  ADMISIÓN HOSPITALARIA   186
Servicio      266     13     Servicio Clínico 8   126
Clave          91     26                    2188   16
Descripcion    91     24       Otra septoplastia   16

In [18]:
df_np.describe(include='object').transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [19]:
df_hi.describe(include='object').transpose()

            count unique                         top freq
Expediente    898    621                      210636   13
Registro      898    728                              134
Egreso        898    720                              144
Elaboracion   898    893          18.Sep.23 11:30:00    2
TipoIngreso   898      4  PROCEDIMIENTO AMBULATORIO   542
Servicio      898     14            Hospital de Día   330
Descripcion   701     24    Broncoscopia fibroóptica  551

## LLM

In [25]:
from dotenv import load_dotenv
load_dotenv()
llm = ChatGroq(model_name="llama3-70b-8192")

In [ ]:
df_hq = SmartDataframe(df_hq, config={"llm": llm})
df_hi = SmartDataframe(df_hi, config={"llm": llm})
df_np = SmartDataframe(df_np, config={"llm": llm})