In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandasai import SmartDataframe
from pandasai import SmartDatalake
from pandasai import Agent
from langchain_groq.chat_models import ChatGroq

In [2]:
df_hq = pd.read_csv("./ds/Procedimiento1Hojadequirofano_20250424_utf-8.csv")
df_np = pd.read_csv("./ds/Procedimiento2NotaPostoperatoria_20250424_utf-8.csv")
df_hi = pd.read_csv("./ds/Procedimiento3Hojadeintervencionismo_20250424_utf-8.csv")

## Ajustar los datos de la Hoja de quirófano

In [3]:
df_hq.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      float64
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Cirugía realizada - CIE 9 Tratamientos - Clave                                           object
Cirugía realizada - CIE 9 Tratamientos - Descripción                                     object
Clave                                                                                    object
Descripción                                                                              object
dtype: object

In [4]:
df_hq = df_hq.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Cirugía realizada - CIE 9 Tratamientos - Clave',
                              'Cirugía realizada - CIE 9 Tratamientos - Descripción'])

In [5]:
df_hq.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Nota postoperatoria

In [6]:
df_np.dtypes

ID Módulo Base                                                                           int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)              object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)     object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)    object
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento                       object
Fecha y Hora Registro                                                                   object
Fecha y Hora de Egreso                                                                  object
Fecha y hora de Elaboración                                                             object
Tipo de Ingreso                                                                         object
Hospitalizado en                                                                        object
Cirugía Realizada                                                                       object
Clave                                                                                   object
Descripción                                                                             object
dtype: object

In [7]:
df_np = df_np.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Fecha de nacimiento',
                              'Cirugía Realizada'])

In [8]:
df_np.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Ajustar datos de la Hoja de intervencionismo

In [9]:
df_hi.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                       object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Procedimiento realizado - CIE 9 Tratamientos - Clave                                    float64
Procedimiento realizado - CIE 9 Tratamientos - Descripción                               object
Clave                                                                                   float64
Descripción                                                                              object
dtype: object

In [10]:
df_hi = df_hi.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Procedimiento realizado - CIE 9 Tratamientos - Clave',
                              'Procedimiento realizado - CIE 9 Tratamientos - Descripción'])

In [11]:
df_hi.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

## Descripción

In [12]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 271
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1169

In [13]:
df_hq = df_hq.dropna(subset="Expediente")
df_hi = df_hi.dropna(subset="Expediente")
df_np = df_np.dropna(subset="Expediente")

In [14]:
print("Datos en hoja de quirofano:",df_hq.shape[0])
print("Datos en hoja de intervencionismo:",df_hi.shape[0])
print("Datos en nota postoperatoria:",df_np.shape[0])
print("Datos HQ + HI:",df_hq.shape[0]+df_hi.shape[0])

Datos en hoja de quirofano: 266
Datos en hoja de intervencionismo: 898
Datos en nota postoperatoria: 1000
Datos HQ + HI: 1164

In [15]:
print(df_np["Clave"].value_counts())

Clave
3142    82
2188    80
3322    45
2187    37
215     32
        ..
3429     1
00G5     1
7        1
348      1
5122     1
Name: count, Length: 220, dtype: int64

In [16]:
df_np.describe().transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [17]:
df_hq.describe(include='object').transpose()

            count unique                     top freq
Registro      266    261                            4
Egreso        266    261                            4
Elaboracion   266    266      30.Nov.23 11:20:00    1
TipoIngreso   266      3  ADMISIÓN HOSPITALARIA   186
Servicio      266     13     Servicio Clínico 8   126
Clave          91     26                    2188   16
Descripcion    91     24       Otra septoplastia   16

In [18]:
df_np.describe(include='object').transpose()

            count unique                                 top freq
Expediente   1000    734                              230563    6
Registro     1000    766                                       57
Egreso       1000    766                                       57
Elaboracion  1000    954                  28.Mar.23 14:47:30    4
TipoIngreso  1000      4              ADMISIÓN HOSPITALARIA   778
Servicio     1000     12                 Servicio Clínico 8   555
Clave        1000    220                                3142   82
Descripcion  1000    213  Laringoscopia y otra traqueoscopia   82

In [19]:
df_hi.describe(include='object').transpose()

            count unique                         top freq
Expediente    898    621                      210636   13
Registro      898    728                              134
Egreso        898    720                              144
Elaboracion   898    893          18.Sep.23 11:30:00    2
TipoIngreso   898      4  PROCEDIMIENTO AMBULATORIO   542
Servicio      898     14            Hospital de Día   330
Descripcion   701     24    Broncoscopia fibroóptica  551

## LLM

In [20]:
from dotenv import load_dotenv
load_dotenv()
llm = ChatGroq(model_name="llama3-70b-8192")

In [28]:
df_hq = SmartDataframe(df_hq, config={"llm": llm})
df_hi = SmartDataframe(df_hi, config={"llm": llm})
df_np = SmartDataframe(df_np, config={"llm": llm})

In [21]:
ai = Agent([df_hq, df_hi, df_np], config={"llm": llm}, memory_size=10)

In [22]:
ai.chat("¿Cuántos Expedientes repetidos existen?")

332

In [23]:
ai.chat("¿Cuántos registros coinciden en Expediente y Registro? Ponlos en una tabla")

     Expediente            Registro
0      248277.0  11.Ene.23 15:33:18
1      236422.0  11.Ene.23 15:48:18
2      209000.0  10.Ene.23 15:32:44
3      243590.0  10.Ene.23 15:23:31
4      248153.0  11.Ene.23 09:40:52
...         ...                 ...
2159     254692  24.Nov.23 01:43:36
2160     221315  01.Dic.23 06:48:57
2161     246005  01.Dic.23 07:47:57
2162     253871  30.Nov.23 15:32:50
2163     250693  06.Nov.23 18:18:13

[1678 rows x 2 columns]

In [24]:
ai.chat("Crea un dataframe llamado df que tenga los registros que coinciden en Expediente y Registro")

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
153,245209.0,04.Jun.23 15:36:02,06.Jun.23 07:38:13,05.Jun.23 10:36:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,NaN,NaN
154,245209.0,04.Jun.23 15:36:02,06.Jun.23 07:38:13,05.Jun.23 11:32:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,NaN,NaN
181,251556.0,20.Jun.23 13:56:25,24.Jul.23 17:25:49,08.Jul.23 13:02:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 3,935A,COLOCACIÓN DE BOMBA DE VACÍO (VAC)
182,251556.0,20.Jun.23 13:56:25,24.Jul.23 17:25:49,08.Jul.23 15:06:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 3,935A,COLOCACIÓN DE BOMBA DE VACÍO (VAC)
272,248583,19.Ene.23 19:22:59,08.Mar.23 00:09:27,03.Feb.23 10:37:00,ADMISIÓN HOSPITALARIA,Servicio Clínico 4,NaN,NaN
...,...,...,...,...,...,...,...,...
2150,254411,24.Nov.23 13:27:29,02.Feb.24 17:59:19,30.Nov.23 18:08:29,ADMISIÓN HOSPITALARIA,Servicio Clínico 4,3179,Otras operaciones de reconstrucción y plástica...
2151,254228,04.Nov.23 01:14:33,22.Dic.23 13:44:12,30.Nov.23 23:09:29,INGRESO A TERAPIA,Servicio Clínico 1,3129,Otra traqueostomía permanente
2154,225141,01.Dic.23 06:46:56,01.Dic.23 18:14:09,01.Dic.23 12:39:45,PROCEDIMIENTO AMBULATORIO,Hospital de Día,3322,Broncoscopia fibroóptica
2155,254411,24.Nov.23 13:27:29,02.Feb.24 17:59:19,01.Dic.23 13:39:13,ADMISIÓN HOSPITALARIA,Servicio Clínico 4,3322,Broncoscopia fibroóptica
2157,225141,01.Dic.23 06:46:56,01.Dic.23 18:14:09,01.Dic.23 15:38:22,PROCEDIMIENTO AMBULATORIO,Hospital de Día,3323,Otra broncoscopia

In [25]:
df = ai.chat("Ordena df por Registro y muéstramelo")

In [26]:
df

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
844,246452,,,14.Jul.23 08:23:00,,,9741.0,Extracción de tubo de toracotomía o de drenaje...
596,246086,,,24.Abr.23 09:07:00,,,3406.0,Drenaje de cavidad pleural por toracoscopía
839,247608,,,13.Jul.23 11:01:00,,,9741.0,Extracción de tubo de toracotomía o de drenaje...
578,246452,,,21.Abr.23 09:33:00,,,3406.0,Drenaje de cavidad pleural por toracoscopía
1257,235402,,,28.Mar.23 15:31:34,,,215,Resección submucosa del tabique nasal (septopl...
...,...,...,...,...,...,...,...,...
1965,254146,30.Oct.23 17:49:53,24.Nov.23 14:13:50,31.Oct.23 17:51:49,ADMISIÓN HOSPITALARIA,Servicio Clínico 7,3452,Decorticación de pulmón por toracoscopía
1586,221778,31.Jul.23 23:14:40,05.Ago.23 10:29:53,03.Ago.23 11:04:45,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,3198,Otras operaciones sobre laringe
1590,221778,31.Jul.23 23:14:40,05.Ago.23 10:29:53,04.Ago.23 06:59:39,ADMISIÓN HOSPITALARIA,Servicio Clínico 8,3198,Otras operaciones sobre laringe
1991,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,339,Otras operaciones sobre pulmón y bronquio
1990,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,332,Procedimientos diagnósticos sobre pulmón y bro...

In [27]:
df.to_csv("./out/df.csv")

In [35]:
df_np.chat("Muestrame las filas con Expediente igual a 254171")

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
826,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,332,Procedimientos diagnósticos sobre pulmón y bro...
827,254171,31.Oct.23 11:19:58,16.Nov.23 17:33:03,06.Nov.23 12:02:43,ADMISIÓN HOSPITALARIA,Servicio Clínico 2,339,Otras operaciones sobre pulmón y bronquio

In [36]:
df_hq.chat("Muestrame las filas con Expediente igual a 254171")

Empty DataFrame
Columns: [Expediente, Registro, Egreso, Elaboracion, TipoIngreso, Servicio, Clave, Descripcion]
Index: []

In [37]:
df_hi.chat("Muestrame las filas con Expediente igual a 254171")

,Expediente,Registro,Egreso,Elaboracion,TipoIngreso,Servicio,Clave,Descripcion
857,254171,04.Dic.23 06:47:17,04.Dic.23 16:43:45,04.Dic.23 13:01:00,PROCEDIMIENTO AMBULATORIO,Hospital de Día,3322.0,Broncoscopia fibroóptica