In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy version: 2.2.5
Pandas version: 2.2.3

In [3]:
df_hq = pd.read_csv("./ds/Procedimiento1Hojadequirofano_20250424_utf-8.csv")
df_np = pd.read_csv("./ds/Procedimiento2NotaPostoperatoria_20250424_utf-8.csv")
df_hi = pd.read_csv("./ds/Procedimiento3Hojadeintervencionismo_20250424_utf-8.csv")

## Ajustar los datos de la Hoja de quirófano

In [4]:
df_hq.shape

(271, 14)

In [5]:
df_hq.describe(include='object').transpose()

,count,unique,top,freq
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre),266,224,MARCO ANTONIO,4
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido),266,167,HERNANDEZ,13
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido),266,173,HERNANDEZ,12
Fecha y Hora Registro,271,261,,9
Fecha y Hora de Egreso,271,261,,9
Fecha y hora de elaboración,271,271,30.Nov.23 11:20:00,1
Tipo de Ingreso,271,3,ADMISIÓN HOSPITALARIA,186
Hospitalizado en,271,13,Servicio Clínico 8,126
Cirugía realizada - CIE 9 Tratamientos - Clave,92,26,2188,16
Cirugía realizada - CIE 9 Tratamientos - Descripción,92,24,Otra septoplastia,16
Clave,92,26,2188,16
Descripción,92,24,Otra septoplastia,16

In [6]:
df_hq.dtypes

ID Módulo Base                                                                            int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      float64
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)               object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)     object
Fecha y Hora Registro                                                                    object
Fecha y Hora de Egreso                                                                   object
Fecha y hora de elaboración                                                              object
Tipo de Ingreso                                                                          object
Hospitalizado en                                                                         object
Cirugía realizada - CIE 9 Tratamientos - Clave                                           object
Cirugía realizada - CIE 9 Tratamientos - Descripción                                     object
Clave                                                                                    object
Descripción                                                                              object
dtype: object

In [7]:
df_hq = df_hq.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Cirugía realizada - CIE 9 Tratamientos - Clave',
                              'Cirugía realizada - CIE 9 Tratamientos - Descripción'])

In [8]:
df_hq.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

In [9]:
df_hq["Servicio"].value_counts()

Servicio
Servicio Clínico 8                      126
Hospital de Día                          67
Servicio Clínico 2                       20
Servicio Clínico 3                       12
Servicio Clínico 4                       11
Servicio Clínico 1                       10
                                          9
Servicio Clínico 10 Recuperación          4
Servicio Clínico 10                       4
Servicio Clínico 7                        3
Quirófanos                                2
Servicio Clínico 10 Postquirúrgicos       2
Unidad de Terapia Intermedia              1
Name: count, dtype: int64

In [10]:
df_hq.info

<bound method DataFrame.info of      Expediente            Registro              Egreso         Elaboracion  \
0      248277.0  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 09:40:00
1      236422.0  11.Ene.23 15:48:18  12.Ene.23 19:05:18  12.Ene.23 08:41:00
2      209000.0  10.Ene.23 15:32:44  12.Ene.23 13:12:16  11.Ene.23 09:52:00
3      243590.0  10.Ene.23 15:23:31  11.Ene.23 18:02:14  11.Ene.23 10:56:00
4      248153.0  11.Ene.23 09:40:52  11.Ene.23 15:29:00  11.Ene.23 13:24:00
..          ...                 ...                 ...                 ...
266    216626.0  25.Oct.23 07:09:38  25.Oct.23 19:03:13  25.Oct.23 09:32:00
267         NaN                                          23.Oct.23 11:35:00
268    250094.0  23.Oct.23 11:08:32  25.Oct.23 14:59:41  24.Oct.23 10:45:00
269    239002.0  01.Nov.23 07:38:17  01.Nov.23 19:34:47  01.Nov.23 10:49:00
270    253011.0  29.Nov.23 15:11:54  03.Dic.23 16:27:53  30.Nov.23 11:20:00

                    TipoIngreso             Servicio Clave  \
0        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
2        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    195
3        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
4    PROCEDIMIENTO AMBULATORIO           Quirófanos   3322
..                          ...                  ...   ...
266  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
267                                                    NaN
268      ADMISIÓN HOSPITALARIA   Servicio Clínico 4   3328
269  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
270      ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN

                   Descripcion
0                          NaN
1                          NaN
2          Otra timpanoplastia
3                          NaN
4     Broncoscopia fibroóptica
..                         ...
266                        NaN
267                        NaN
268  Biopsia abierta de pulmón
269                        NaN
270                        NaN

[271 rows x 8 columns]>

In [11]:
df_hq.dropna(subset="Expediente").info

<bound method DataFrame.info of      Expediente            Registro              Egreso         Elaboracion  \
0      248277.0  11.Ene.23 15:33:18  12.Ene.23 19:02:22  12.Ene.23 09:40:00
1      236422.0  11.Ene.23 15:48:18  12.Ene.23 19:05:18  12.Ene.23 08:41:00
2      209000.0  10.Ene.23 15:32:44  12.Ene.23 13:12:16  11.Ene.23 09:52:00
3      243590.0  10.Ene.23 15:23:31  11.Ene.23 18:02:14  11.Ene.23 10:56:00
4      248153.0  11.Ene.23 09:40:52  11.Ene.23 15:29:00  11.Ene.23 13:24:00
..          ...                 ...                 ...                 ...
265    253651.0  09.Oct.23 12:51:02  28.Oct.23 14:13:57  17.Oct.23 11:00:00
266    216626.0  25.Oct.23 07:09:38  25.Oct.23 19:03:13  25.Oct.23 09:32:00
268    250094.0  23.Oct.23 11:08:32  25.Oct.23 14:59:41  24.Oct.23 10:45:00
269    239002.0  01.Nov.23 07:38:17  01.Nov.23 19:34:47  01.Nov.23 10:49:00
270    253011.0  29.Nov.23 15:11:54  03.Dic.23 16:27:53  30.Nov.23 11:20:00

                    TipoIngreso             Servicio Clave  \
0        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
1        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
2        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    195
3        ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN
4    PROCEDIMIENTO AMBULATORIO           Quirófanos   3322
..                          ...                  ...   ...
265      ADMISIÓN HOSPITALARIA   Servicio Clínico 2   3241
266  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
268      ADMISIÓN HOSPITALARIA   Servicio Clínico 4   3328
269  PROCEDIMIENTO AMBULATORIO      Hospital de Día    NaN
270      ADMISIÓN HOSPITALARIA   Servicio Clínico 8    NaN

                               Descripcion
0                                      NaN
1                                      NaN
2                      Otra timpanoplastia
3                                      NaN
4                 Broncoscopia fibroóptica
..                                     ...
265  Lobectomía de pulmón por toracoscopía
266                                    NaN
268              Biopsia abierta de pulmón
269                                    NaN
270                                    NaN

[266 rows x 8 columns]>

## Ajustar datos de la Nota postoperatoria

In [12]:
df_np.shape

(1000, 14)

In [13]:
df_np.describe(include='object').transpose()

,count,unique,top,freq
Expediente / Paciente - Expediente Paciente - Número de Expediente,1000,734,230563,6
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre),1000,559,ALEJANDRO,10
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido),1000,355,HERNANDEZ,40
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido),987,374,HERNANDEZ,33
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento,1000,726,1992-08-05,6
Fecha y Hora Registro,1000,766,,57
Fecha y Hora de Egreso,1000,766,,57
Fecha y hora de Elaboración,1000,954,28.Mar.23 14:47:30,4
Tipo de Ingreso,1000,4,ADMISIÓN HOSPITALARIA,778
Hospitalizado en,1000,12,Servicio Clínico 8,555
Cirugía Realizada,1000,703,RINOSEPTUMPLASTIA FUNCIONAL + ABLACIÓN DE CORN...,29
Clave,1000,220,3142,82
Descripción,1000,213,Laringoscopia y otra traqueoscopia,82

In [14]:
df_np.dtypes

ID Módulo Base                                                                           int64
Expediente / Paciente - Expediente Paciente - Número de Expediente                      object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)              object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)     object
Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)    object
Expediente / Paciente - Expediente Paciente - Fecha de nacimiento                       object
Fecha y Hora Registro                                                                   object
Fecha y Hora de Egreso                                                                  object
Fecha y hora de Elaboración                                                             object
Tipo de Ingreso                                                                         object
Hospitalizado en                                                                        object
Cirugía Realizada                                                                       object
Clave                                                                                   object
Descripción                                                                             object
dtype: object

In [16]:
df_np = df_np.drop(columns = ['ID Módulo Base',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Nombre)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Primer Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Nombre del Paciente (Segundo Apellido)',
                              'Expediente / Paciente - Expediente Paciente - Fecha de nacimiento',
                              'Cirugía Realizada'])

In [17]:
df_np.columns = ['Expediente', 'Registro', 'Egreso', 'Elaboracion', 'TipoIngreso', 'Servicio', 'Clave', 'Descripcion']

In [ ]:
df_np.info